# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fc053da335d10e51edbe592ae56a74e4e335d2d6a265cf1c6fb3e17afca8beb3f48ff6e481dbe7b8ffbc039edb4921e1c553255d78e2fc6eed97e31a5bf37e0

test:
  secret_key_base: b877cee92f344a5e9617fdc26df75cef25e3cfbf19c590a3d4fc73e8c3fc904be90c8758b4c3313260fb5a6e34e6673ba861fc976ed811014bfb95f60c2c4894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
